ansible-playbook /home/ansibleadmin/cosc2767-rmit-store/buildAndPushMariadb.yml
ansible-playbook /home/ansibleadmin/cosc2767-rmit-store/buildAndPushApache.yml
sleep 10
ansible-playbook /home/ansibleadmin/cosc2767-rmit-store/pullMariadbToCreateContainer.yml
sleep 10 
ansible-playbook /home/ansibleadmin/cosc2767-rmit-store/pullApacheToCreateContainer.yml
sleep 10
python /home/ansibleadmin/cosc2767-rmit-store/test-ui.py
sleep 10
ansible-playbook /home/ansibleadmin/cosc2767-rmit-store/pullMariadbProd.yml
sleep 10
ansible-playbook /home/ansibleadmin/cosc2767-rmit-store/pullApacheProd.yml
