# RMIT University Vietnam
# Course: COSC2767 Systems Deployment and Operations
# Semester: 2022B
# Assessment: Assignment 3
# Author: Nguyen Quoc Huy
# ID: s3818764
# Created  date: 18/09/2022
# Last modified: 18/09/2022
# Acknowledgement: Google

- hosts: ansibleserver
  tasks:
    - name: start docker
      command: sudo service docker start
    - name: create docker image
      command: docker build -t mariadb-image-a3:latest ./cosc2767-rmit-store/sql-scripts/
    - name: create tag to push the image to dockerhub
      command: docker tag mariadb-image-a3:latest quochuynguyen/mariadb-image-a3:latest
    - name: push the docker image to dockerhub
      command: docker push quochuynguyen/mariadb-image-a3:latest
