- hosts: ansibleserver
  tasks:
    - name: create docker image
      command: docker build -t apache-test-a3:latest ./cosc2767-rmit-store --build-arg DBHOST=54.166.41.119
    - name: create tag to push the image to dockerhub
      command: docker tag apache-test-a3:latest quochuynguyen/apache-test-a3:latest
    - name: push the docker image to dockerhub
      command: docker push quochuynguyen/apache-test-a3:latest
