- hosts: mariadbprod
  tasks:
    - name: stop the existing container
      command: docker stop mariadb-container
      ignore_errors: yes
    - name: remove the existing container
      command: docker rm mariadb-container
      ignore_errors: yes
    - name: remove the existing image
      command: docker rmi quochuynguyen/mariadb-a3:latest
      ignore_errors: yes
    - name: create docker container by using the image on Dockerhub
      command: docker run -d --name mariadb-container -p 3306:3306 quochuynguyen/mariadb-a3:latest
