- hosts: mariadbserver
  tasks:
    - name: start docker
      command: sudo service docker start
    - name: stop the existing container
      command: docker stop $(docker ps -a -q)
      ignore_errors: yes
    - name: remove the existing container
      command: docker rm -vf $(docker ps -aq)
      ignore_errors: yes
    - name: remove the existing image
      command: docker rmi -f $(docker images -aq)
      ignore_errors: yes
    - name: create docker container by using the image on Dockerhub
      command: docker run -d --name mariadb-container -p 3306:3306 quochuynguyen/mariadb-image-a3:latest
