- hosts: apacheprod
  tasks:
    - name: stop the existing container
      command: docker stop apache-container
      ignore_errors: yes
    - name: remove the existing container
      command: docker rm apache-container
      ignore_errors: yes
    - name: remove the existing image
      command: docker rmi quochuynguyen/apache-a3:latest
      ignore_errors: yes
    - name: create docker container by using the image on Dockerhub
      command: docker run -d --name apache-container -e DBHOST='44.206.236.31' -p 80:80 quochuynguyen/apache-a3:latest
