# RMIT University Vietnam
# Course: COSC2767 Systems Deployment and Operations
# Semester: 2022B
# Assessment: Assignment 3
# Author: Nguyen Quoc Huy
# ID: s3818764
# Created  date: 18/09/2022
# Last modified: 18/09/2022
# Acknowledgement: Google

- hosts: mariadbprod
  tasks:
    - name: start docker
      command: sudo service docker start
    - name: stop the existing container
      command: docker stop mariadb-container
      ignore_errors: yes
    - name: remove the existing container
      command: docker rm mariadb-container
      ignore_errors: yes
    - name: remove the existing image
      command: docker rmi quochuynguyen/mariadb-image-a3:latest
      ignore_errors: yes
    - name: create docker container by using the image on Dockerhub
      command: docker run -d --name mariadb-container -p 3306:3306 quochuynguyen/mariadb-image-a3:latest
