# RMIT University Vietnam
# Course: COSC2767 Systems Deployment and Operations
# Semester: 2022B
# Assessment: Assignment 3
# Author: Nguyen Quoc Huy
# ID: s3818764
# Created  date: 18/09/2022
# Last modified: 18/09/2022
# Acknowledgement: Google

- hosts: apacheprod
  tasks:
    - name: start docker
      command: sudo service docker start
    - name: stop the existing container
      command: docker stop apache-container
      ignore_errors: yes
    - name: remove the existing container
      command: docker rm apache-container
      ignore_errors: yes
    - name: remove the existing image
      command: docker rmi quochuynguyen/apache-a3:latest
      ignore_errors: yes
    - name: create docker container by using the image on Dockerhub
      command: docker run -d --name apache-container -e DBHOST='52.23.70.92' -p 80:80 quochuynguyen/apache-a3:latest
